number = int(input())
stroka = str(number)
spisok = list(stroka)
print(spisok)
# sorted_spisok = reversed(sorted(spisok))
# sorted_spisok = sorted(spisok, reverse=True)
spisok.sort()
# spisok.reverse()
sorted_spisok = spisok[::-1]
res_stroka = int("".join(sorted_spisok))
print(res_stroka)